"""account view preference

Revision ID: 03561850c1e4
Revises: 4de2dfda3fa6
Create Date: 2026-09-28 01:06:22.523918
"""
from alembic import op
import sqlalchemy as sa


revision = '03561850c1e4'
down_revision = '4de2dfda3fa6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('view_preference', sa.String(length=20), nullable=False, server_default='buyer'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'view_preference')
    # ### end Alembic commands ###
