"""location email attempts and report uniqueness

Revision ID: 4de2dfda3fa6
Revises: e0a325c6997f
Create Date: 2026-09-28 00:56:55.311997
"""
from alembic import op
import sqlalchemy as sa


revision = '4de2dfda3fa6'
down_revision = 'e0a325c6997f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('email_codes', sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'))
    with op.batch_alter_table('hygiene_reports') as batch_op:
        batch_op.create_unique_constraint('uq_hygiene_reports_order_buyer', ['order_id', 'buyer_id'])
    op.add_column('kitchens', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('kitchens', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kitchens', 'longitude')
    op.drop_column('kitchens', 'latitude')
    with op.batch_alter_table('hygiene_reports') as batch_op:
        batch_op.drop_constraint('uq_hygiene_reports_order_buyer', type_='unique')
    op.drop_column('email_codes', 'attempts')
    op.drop_column('addresses', 'longitude')
    op.drop_column('addresses', 'latitude')
    # ### end Alembic commands ###
